"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {apiRequest} from '@/lib/api-client';
export function CleanupTestData({period,onDeleted}:{period?:{from:string;to:string;department?:string};onDeleted?:()=>void}={}){
 const endpoint='/api/admin/cleanup'+(period?'?'+new URLSearchParams({...period,department:period.department||''}):'');
 const phrase=period?'HAPUS PERIODE':'HAPUS DATA PERCOBAAN';
 const [ids,setIds]=useState<string[]|null>(null),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function inspect(){setBusy(true);try{const r=await apiRequest<{ids:string[]}>(endpoint);setIds(r.ids);setConfirmation('');setMessage(r.ids.length?'Periksa jumlah, lalu ketik konfirmasi sebelum menghapus.':'Tidak ada data kunjungan. Tidak ada kunjungan dalam pilihan ini.');}catch(e){setMessage(e instanceof Error?e.message:'Daftar belum dapat diperiksa.');}finally{setBusy(false);}}
 async function remove(){if(!ids)return;setBusy(true);try{const r=await apiRequest<{deleted:number}>('/api/admin/cleanup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids,confirmation,...period})});const remaining=await apiRequest<{ids:string[]}>(endpoint);onDeleted?.();setIds(remaining.ids);setConfirmation('');setMessage(`${r.deleted} kunjungan dan data terkait dihapus. ${remaining.ids.length?'Masih ada data; periksa sebelum menghapus lagi.':'Tidak ada kunjungan tersisa dalam pilihan ini.'}`);}catch(e){setIds(null);setMessage(e instanceof Error?e.message:'Pembersihan belum selesai.');}finally{setBusy(false);}}
 return <section className="mt-6 rounded-2xl border border-rose-200 bg-white p-5"><h2 className="text-lg font-bold text-rose-900">{period?'Hapus data sesuai periode':'Bersihkan data percobaan'}</h2><p className="mt-2 text-sm text-slate-700">Menghapus permanen kunjungan yang diperiksa, tanda tangan, ulasan, riwayat layanan, dan notifikasi terkait. {period?`Periode ${period.from} sampai ${period.to}. Unduh laporan sebelum menghapus jika perlu menyimpan arsip.`:'Gunakan hanya sebelum data operasional asli masuk.'} Akun, bidang, layanan, pegawai, dan koneksi notifikasi dipertahankan.</p><Button className="mt-4" variant="outline" disabled={busy} onClick={inspect}>Periksa data tamu</Button>{ids&&ids.length>0&&<div className="mt-4 space-y-3"><p className="font-semibold">{ids.length} kunjungan akan dihapus (maksimal 500 per proses).</p><label className="block text-sm" htmlFor="cleanup-confirm">Ketik {phrase}</label><Input id="cleanup-confirm" value={confirmation} onChange={e=>setConfirmation(e.target.value)} disabled={busy}/><Button variant="destructive" disabled={busy||confirmation!==phrase} onClick={remove}>{busy?'Membersihkan…':'Hapus permanen data yang diperiksa'}</Button></div>}{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</section>;
}
